name       : python-jupyter-server
version    : 1.23.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_server/jupyter_server-1.23.3.tar.gz : f7f7a2f9d36f4150ad125afef0e20b1c76c8ff83eb5e39fb02d3b9df0f9b79ab
homepage   : https://github.com/jupyter-server/jupyter_server
license    : BSD-3-Clause
component  : programming.python
summary    : The backend—i.e. core services, APIs, and REST endpoints—to Jupyter web applications
description: |
    The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila.
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-anyio
    - python-argon2-cffi
    - python-jupyter_client
    - python-nbconvert
    - python-prometheus_client
    - python-send2trash
    - python-terminado
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
